---
- hosts: local
  connection: local
  remote_user: abhishek
  become_method: sudo
  gather_facts: no
  vars:
    instance_ids: "{{ instance_ids }}"
    state: "{{ state }}" # present, absent, running, stopped
  vars_files:
  - files/awscreds.yml 

  tasks:
  - name: Change state of a given EC2 instance
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws_region }}"
      instance_ids: "{{ instance_ids }}"
      state: "{{ state }}"

