---
- hosts: local
  connection: local
  remote_user: abhishek
  become_method: sudo
  gather_facts: no
  vars:
    instance_ids: "{{ instance_ids }}"
    state: "{{ state }}" # present, absent, running, stopped

  tasks:
  - name: Change state of a given EC2 instance
    ec2:
      region: ap-southeast-1
      instance_ids: "{{ instance_ids }}"
      state: "{{ state }}"

