--- # AWS EC2 Communication Shell Playbook
- hosts: aws
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
  - name: Execute a shell command 
    shell: ls -al ~
    register: result

  - name: Display the result in JSON 
    debug: var=result  
